# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
    # Enable version updates for Composer
    - package-ecosystem: "composer"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "sunday"
      open-pull-requests-limit: 10
      groups:
          symfony:
              patterns:
                  - "symfony/*"
          doctrine:
              patterns:
                  - "doctrine/*"
      ignore:
          - dependency-name: "roave/security-advisories"

    # Enable version updates for npm (JS dev tooling)
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "sunday"
      groups:
          eslint:
              patterns:
                  - "eslint"
                  - "@eslint/*"
                  - "eslint-config-prettier"
                  - "globals"
                  - "prettier"

    # Enable version updates for GitHub Actions
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "sunday"
