nelmio_security:
    clickjacking:
        paths:
            '^/.*': DENY

    content_type:
        nosniff: true

    referrer_policy:
        enabled: true
        policies:
            - 'no-referrer'
            - 'strict-origin-when-cross-origin'

    permissions_policy:
        enabled: true
        policies:
            geolocation: []
            microphone: []
            camera: []

when@prod:
    nelmio_security:
        forced_ssl:
            enabled: true
            hsts_max_age: 31536000
            hsts_subdomains: true
            hsts_preload: false
        csp:
            report:
                default-src: ["'self'"]
                base-uri: ["'self'"]
                object-src: ["'none'"]
                script-src: ["'self'", "'unsafe-inline'", "data:"]
                style-src: ["'self'", "'unsafe-inline'"]
                img-src: ["'self'", "data:", "https://*.tile.openstreetmap.org"]
                font-src: ["'self'", "data:"]
                connect-src: ["'self'", "https://*.tile.openstreetmap.org", "https://*.ingest.sentry.io"]
                form-action: ["'self'"]
