nelmio_security:
    clickjacking:
        paths:
            '^/.*': DENY

    content_type:
        nosniff: true

    referrer_policy:
        enabled: true
        policies:
            - 'no-referrer'
            - 'strict-origin-when-cross-origin'

    permissions_policy:
        enabled: true
        policies:
            geolocation: []
            microphone: []
            camera: []

when@prod:
    nelmio_security:
        forced_ssl:
            enabled: true
            hsts_max_age: 31536000
            hsts_subdomains: true
            hsts_preload: false
