twig:
    file_name_pattern: '*.twig'

    date:
        format: 'd.m.Y'
        interval_format: '%%d days'
        timezone: 'Europe/Berlin'

    globals:
        'app_version': '%app.version%'
        'app_title': '%app.title%'
        'app_short_title': '%app.short_title%'
        'app_blog_title': '%app.blog.title%'
        'app_blog_description': '%app.blog.description%'
        'app_mailer_from': '%app.mailer_from%'

    paths:
        '%kernel.project_dir%/src/Admin/UI/Twig/templates': Admin
        '%kernel.project_dir%/src/Allocation/UI/Twig/templates': Allocation
        '%kernel.project_dir%/src/Content/UI/Twig/templates': Content
        '%kernel.project_dir%/src/Engagement/UI/Twig/templates': Engagement
        '%kernel.project_dir%/src/Feedback/UI/Twig/templates': Feedback
        '%kernel.project_dir%/src/Import/UI/Twig/templates': Import
        '%kernel.project_dir%/src/User/UI/Twig/templates': User
        '%kernel.project_dir%/src/Shared/UI/Twig/templates': Shared
        '%kernel.project_dir%/src/Statistics/UI/Twig/templates': Statistics

    form_themes:
        - 'bootstrap_5_layout.html.twig'
        - '@Shared/form/password_visibility_theme.html.twig'

when@test:
    twig:
        strict_variables: true
