<?php

declare(strict_types=1);

namespace App\Tests\Content\Unit\Blog;

use App\Content\Application\Blog\PostSlugExistsChecker;
use App\Content\Application\Blog\PostSlugResolver;
use App\Content\Application\Slug\SlugGenerator;
use App\Content\Domain\Entity\Post;
use PHPUnit\Framework\TestCase;
use Symfony\Component\String\Slugger\AsciiSlugger;

final class PostSlugResolverTest extends TestCase
{
    public function testGeneratesSlugFromTitleWhenSlugIsEmpty(): void
    {
        $resolver = $this->createResolver(static fn (): bool => false);

        $post = new Post()->setTitle('My First Post');

        $resolver->resolve($post);

        self::assertSame('my-first-post', $post->getSlug());
    }

    public function testPreservesManualSlugAsEntered(): void
    {
        $wasCalled = false;
        $resolver = $this->createResolver(static function () use (&$wasCalled): bool {
            $wasCalled = true;

            return false;
        });

        $post = new Post()
            ->setTitle('Changed Title')
            ->setSlug('my-custom-slug');

        $resolver->resolve($post);

        self::assertSame('my-custom-slug', $post->getSlug());
        self::assertFalse($wasCalled, 'slugExists must not be called for manual slugs');
    }

    public function testTrimsWhitespaceFromManualSlug(): void
    {
        $wasCalled = false;
        $resolver = $this->createResolver(static function () use (&$wasCalled): bool {
            $wasCalled = true;

            return false;
        });

        $post = new Post()
            ->setTitle('Changed Title')
            ->setSlug('  trimmed-slug  ');

        $resolver->resolve($post);

        self::assertSame('trimmed-slug', $post->getSlug());
        self::assertFalse($wasCalled, 'slugExists must not be called for manual slugs');
    }

    public function testTitleChangeDoesNotOverwriteManualSlug(): void
    {
        $wasCalled = false;
        $resolver = $this->createResolver(static function () use (&$wasCalled): bool {
            $wasCalled = true;

            return false;
        });

        $post = new Post()
            ->setTitle('Completely Different Title')
            ->setSlug('fixed-slug');

        $resolver->resolve($post);

        self::assertSame('fixed-slug', $post->getSlug());
        self::assertFalse($wasCalled, 'slugExists must not be called for manual slugs');
    }

    public function testEnsureUniqueOnlyForAutoGeneratedSlugs(): void
    {
        $existing = ['taken-slug', 'taken-slug-2'];
        $resolver = $this->createResolver(
            static fn (string $candidate): bool => in_array($candidate, $existing, true),
        );

        $post = new Post()->setTitle('Taken Slug');

        $resolver->resolve($post);

        self::assertSame('taken-slug-3', $post->getSlug());
    }

    public function testPassesExcludeIdWhenUpdatingExistingPost(): void
    {
        $resolver = $this->createResolver(
            static fn (string $candidate, ?int $excludeId): bool => 'my-post' === $candidate && 42 !== $excludeId,
        );

        $post = new Post()
            ->setTitle('My Post')
            ->setSlug('');

        $resolver->resolve($post, 42);

        self::assertSame('my-post', $post->getSlug());
    }

    /**
     * @param callable(string, ?int): bool $slugExists
     */
    private function createResolver(callable $slugExists): PostSlugResolver
    {
        $checker = new class($slugExists) implements PostSlugExistsChecker {
            /** @param callable(string, ?int): bool $slugExists */
            public function __construct(
                private $slugExists,
            ) {
            }

            public function slugExists(string $slug, ?int $excludeId = null): bool
            {
                return ($this->slugExists)($slug, $excludeId);
            }
        };

        return new PostSlugResolver(new SlugGenerator(new AsciiSlugger()), $checker);
    }
}
