<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260621173427 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add audit fields, nullable slug, and favorites for Analysis Explorer saved views.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE saved_explorer_view ALTER slug DROP NOT NULL');
        $this->addSql('ALTER TABLE saved_explorer_view ADD created_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE saved_explorer_view ADD updated_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE saved_explorer_view ADD CONSTRAINT FK_SAVED_EXPLORER_VIEW_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE saved_explorer_view ADD CONSTRAINT FK_SAVED_EXPLORER_VIEW_UPDATED_BY FOREIGN KEY (updated_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_SAVED_EXPLORER_VIEW_CREATED_BY ON saved_explorer_view (created_by_id)');
        $this->addSql('CREATE INDEX IDX_SAVED_EXPLORER_VIEW_UPDATED_BY ON saved_explorer_view (updated_by_id)');
        $this->addSql('CREATE TABLE saved_explorer_view_favorite (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, saved_explorer_view_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_SAVED_EXPLORER_VIEW_FAVORITE_USER ON saved_explorer_view_favorite (user_id)');
        $this->addSql('CREATE INDEX IDX_SAVED_EXPLORER_VIEW_FAVORITE_VIEW ON saved_explorer_view_favorite (saved_explorer_view_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_saved_explorer_view_favorite ON saved_explorer_view_favorite (user_id, saved_explorer_view_id)');
        $this->addSql('ALTER TABLE saved_explorer_view_favorite ADD CONSTRAINT FK_SAVED_EXPLORER_VIEW_FAVORITE_USER FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE saved_explorer_view_favorite ADD CONSTRAINT FK_SAVED_EXPLORER_VIEW_FAVORITE_VIEW FOREIGN KEY (saved_explorer_view_id) REFERENCES saved_explorer_view (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE saved_explorer_view_favorite DROP CONSTRAINT FK_SAVED_EXPLORER_VIEW_FAVORITE_USER');
        $this->addSql('ALTER TABLE saved_explorer_view_favorite DROP CONSTRAINT FK_SAVED_EXPLORER_VIEW_FAVORITE_VIEW');
        $this->addSql('DROP TABLE saved_explorer_view_favorite');
        $this->addSql('ALTER TABLE saved_explorer_view DROP CONSTRAINT FK_SAVED_EXPLORER_VIEW_CREATED_BY');
        $this->addSql('ALTER TABLE saved_explorer_view DROP CONSTRAINT FK_SAVED_EXPLORER_VIEW_UPDATED_BY');
        $this->addSql('DROP INDEX IDX_SAVED_EXPLORER_VIEW_CREATED_BY');
        $this->addSql('DROP INDEX IDX_SAVED_EXPLORER_VIEW_UPDATED_BY');
        $this->addSql('ALTER TABLE saved_explorer_view DROP created_by_id');
        $this->addSql('ALTER TABLE saved_explorer_view DROP updated_by_id');
        $this->addSql('ALTER TABLE saved_explorer_view ALTER slug SET NOT NULL');
    }
}
