<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260315120732 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add secondary_transport table and allocation.secondary_transport_id';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE secondary_transport (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by_id INT NOT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_secondary_transport_created_by ON secondary_transport (created_by_id)');
        $this->addSql('CREATE INDEX IDX_secondary_transport_updated_by ON secondary_transport (updated_by_id)');
        $this->addSql('ALTER TABLE secondary_transport ADD CONSTRAINT FK_secondary_transport_created_by FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE secondary_transport ADD CONSTRAINT FK_secondary_transport_updated_by FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE allocation ADD secondary_transport_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE allocation ADD CONSTRAINT FK_allocation_secondary_transport FOREIGN KEY (secondary_transport_id) REFERENCES secondary_transport (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_allocation_secondary_transport ON allocation (secondary_transport_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE allocation DROP CONSTRAINT FK_allocation_secondary_transport');
        $this->addSql('DROP INDEX IDX_allocation_secondary_transport');
        $this->addSql('ALTER TABLE allocation DROP secondary_transport_id');
        $this->addSql('ALTER TABLE secondary_transport DROP CONSTRAINT FK_secondary_transport_created_by');
        $this->addSql('ALTER TABLE secondary_transport DROP CONSTRAINT FK_secondary_transport_updated_by');
        $this->addSql('DROP TABLE secondary_transport');
    }
}
