<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250907114708 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE department (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by_id INT NOT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CD1DE18AB03A8386 ON department (created_by_id)');
        $this->addSql('CREATE INDEX IDX_CD1DE18A896DBBDE ON department (updated_by_id)');
        $this->addSql('CREATE TABLE speciality (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by_id INT NOT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F3D7A08EB03A8386 ON speciality (created_by_id)');
        $this->addSql('CREATE INDEX IDX_F3D7A08E896DBBDE ON speciality (updated_by_id)');
        $this->addSql('ALTER TABLE department ADD CONSTRAINT FK_CD1DE18AB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE department ADD CONSTRAINT FK_CD1DE18A896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE speciality ADD CONSTRAINT FK_F3D7A08EB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE speciality ADD CONSTRAINT FK_F3D7A08E896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE allocation ADD department_was_closed BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE allocation ADD speciality_id INT NOT NULL');
        $this->addSql('ALTER TABLE allocation ADD department_id INT NOT NULL');
        $this->addSql('ALTER TABLE allocation ADD CONSTRAINT FK_5C44232A3B5A08D7 FOREIGN KEY (speciality_id) REFERENCES speciality (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE allocation ADD CONSTRAINT FK_5C44232AAE80F5DF FOREIGN KEY (department_id) REFERENCES department (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_5C44232A3B5A08D7 ON allocation (speciality_id)');
        $this->addSql('CREATE INDEX IDX_5C44232AAE80F5DF ON allocation (department_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE department DROP CONSTRAINT FK_CD1DE18AB03A8386');
        $this->addSql('ALTER TABLE department DROP CONSTRAINT FK_CD1DE18A896DBBDE');
        $this->addSql('ALTER TABLE speciality DROP CONSTRAINT FK_F3D7A08EB03A8386');
        $this->addSql('ALTER TABLE speciality DROP CONSTRAINT FK_F3D7A08E896DBBDE');
        $this->addSql('DROP TABLE department');
        $this->addSql('DROP TABLE speciality');
        $this->addSql('ALTER TABLE allocation DROP CONSTRAINT FK_5C44232A3B5A08D7');
        $this->addSql('ALTER TABLE allocation DROP CONSTRAINT FK_5C44232AAE80F5DF');
        $this->addSql('DROP INDEX IDX_5C44232A3B5A08D7');
        $this->addSql('DROP INDEX IDX_5C44232AAE80F5DF');
        $this->addSql('ALTER TABLE allocation DROP department_was_closed');
        $this->addSql('ALTER TABLE allocation DROP speciality_id');
        $this->addSql('ALTER TABLE allocation DROP department_id');
    }
}
