<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260423152505 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add entities for the blog, including posts, categories, tags, comments';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE post (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(180) NOT NULL, slug VARCHAR(200) NOT NULL, content TEXT NOT NULL, status VARCHAR(255) NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, category_id INT NOT NULL, created_by_id INT NOT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5A8A6C8D989D9B62 ON post (slug)');
        $this->addSql('CREATE INDEX idx_post_status ON post (status)');
        $this->addSql('CREATE INDEX idx_post_published_at ON post (published_at)');
        $this->addSql('CREATE INDEX IDX_5A8A6C8D12469DE2 ON post (category_id)');
        $this->addSql('CREATE INDEX IDX_5A8A6C8DB03A8386 ON post (created_by_id)');
        $this->addSql('CREATE INDEX IDX_5A8A6C8D896DBBDE ON post (updated_by_id)');
        $this->addSql('CREATE TABLE post_post_tag (post_id INT NOT NULL, post_tag_id INT NOT NULL, PRIMARY KEY (post_id, post_tag_id))');
        $this->addSql('CREATE INDEX IDX_E523B3514B89032C ON post_post_tag (post_id)');
        $this->addSql('CREATE INDEX IDX_E523B3518AF08774 ON post_post_tag (post_tag_id)');
        $this->addSql('CREATE TABLE post_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, slug VARCHAR(150) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by_id INT NOT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B9A190605E237E06 ON post_category (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B9A19060989D9B62 ON post_category (slug)');
        $this->addSql('CREATE INDEX IDX_B9A19060B03A8386 ON post_category (created_by_id)');
        $this->addSql('CREATE INDEX IDX_B9A19060896DBBDE ON post_category (updated_by_id)');
        $this->addSql('CREATE TABLE post_comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, post_id INT NOT NULL, parent_id INT DEFAULT NULL, author_id INT NOT NULL, created_by_id INT NOT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A99CE55F4B89032C ON post_comment (post_id)');
        $this->addSql('CREATE INDEX IDX_A99CE55F727ACA70 ON post_comment (parent_id)');
        $this->addSql('CREATE INDEX IDX_A99CE55FF675F31B ON post_comment (author_id)');
        $this->addSql('CREATE INDEX IDX_A99CE55FB03A8386 ON post_comment (created_by_id)');
        $this->addSql('CREATE INDEX IDX_A99CE55F896DBBDE ON post_comment (updated_by_id)');
        $this->addSql('CREATE TABLE post_tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, slug VARCHAR(150) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by_id INT NOT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5ACE3AF05E237E06 ON post_tag (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5ACE3AF0989D9B62 ON post_tag (slug)');
        $this->addSql('CREATE INDEX IDX_5ACE3AF0B03A8386 ON post_tag (created_by_id)');
        $this->addSql('CREATE INDEX IDX_5ACE3AF0896DBBDE ON post_tag (updated_by_id)');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8D12469DE2 FOREIGN KEY (category_id) REFERENCES post_category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8DB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8D896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE post_post_tag ADD CONSTRAINT FK_E523B3514B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_post_tag ADD CONSTRAINT FK_E523B3518AF08774 FOREIGN KEY (post_tag_id) REFERENCES post_tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_category ADD CONSTRAINT FK_B9A19060B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE post_category ADD CONSTRAINT FK_B9A19060896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE post_comment ADD CONSTRAINT FK_A99CE55F4B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE post_comment ADD CONSTRAINT FK_A99CE55F727ACA70 FOREIGN KEY (parent_id) REFERENCES post_comment (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE post_comment ADD CONSTRAINT FK_A99CE55FF675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE post_comment ADD CONSTRAINT FK_A99CE55FB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE post_comment ADD CONSTRAINT FK_A99CE55F896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE post_tag ADD CONSTRAINT FK_5ACE3AF0B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE post_tag ADD CONSTRAINT FK_5ACE3AF0896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE post DROP CONSTRAINT FK_5A8A6C8D12469DE2');
        $this->addSql('ALTER TABLE post DROP CONSTRAINT FK_5A8A6C8DB03A8386');
        $this->addSql('ALTER TABLE post DROP CONSTRAINT FK_5A8A6C8D896DBBDE');
        $this->addSql('ALTER TABLE post_post_tag DROP CONSTRAINT FK_E523B3514B89032C');
        $this->addSql('ALTER TABLE post_post_tag DROP CONSTRAINT FK_E523B3518AF08774');
        $this->addSql('ALTER TABLE post_category DROP CONSTRAINT FK_B9A19060B03A8386');
        $this->addSql('ALTER TABLE post_category DROP CONSTRAINT FK_B9A19060896DBBDE');
        $this->addSql('ALTER TABLE post_comment DROP CONSTRAINT FK_A99CE55F4B89032C');
        $this->addSql('ALTER TABLE post_comment DROP CONSTRAINT FK_A99CE55F727ACA70');
        $this->addSql('ALTER TABLE post_comment DROP CONSTRAINT FK_A99CE55FF675F31B');
        $this->addSql('ALTER TABLE post_comment DROP CONSTRAINT FK_A99CE55FB03A8386');
        $this->addSql('ALTER TABLE post_comment DROP CONSTRAINT FK_A99CE55F896DBBDE');
        $this->addSql('ALTER TABLE post_tag DROP CONSTRAINT FK_5ACE3AF0B03A8386');
        $this->addSql('ALTER TABLE post_tag DROP CONSTRAINT FK_5ACE3AF0896DBBDE');
        $this->addSql('DROP TABLE post');
        $this->addSql('DROP TABLE post_post_tag');
        $this->addSql('DROP TABLE post_category');
        $this->addSql('DROP TABLE post_comment');
        $this->addSql('DROP TABLE post_tag');
    }
}
