<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260423193324 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add page table for hierarchical CMS pages';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE page (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(180) NOT NULL, path VARCHAR(500) NOT NULL, status VARCHAR(32) NOT NULL, visibility VARCHAR(32) NOT NULL, sort_order INT DEFAULT 0 NOT NULL, content JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_140AB620727ACA70 ON page (parent_id)');
        $this->addSql('CREATE INDEX idx_page_parent_sort ON page (parent_id, sort_order)');
        $this->addSql('CREATE UNIQUE INDEX uniq_page_path ON page (path)');
        $this->addSql('CREATE UNIQUE INDEX uniq_page_parent_slug ON page (parent_id, slug)');
        $this->addSql('ALTER TABLE page ADD CONSTRAINT FK_140AB620727ACA70 FOREIGN KEY (parent_id) REFERENCES page (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE page DROP CONSTRAINT FK_140AB620727ACA70');
        $this->addSql('DROP TABLE page');
    }
}
