<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261006113000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Separate closure source rows, analysis intervals and stable events, and rebuild the volume projection grain.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE import ADD export_starts_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE import ADD export_ends_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');

        $this->addSql(<<<'SQL'
CREATE TABLE closure_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    hospital_id INT NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    grouping_key VARCHAR(160) NOT NULL,
    source_group_id VARCHAR(32) DEFAULT NULL,
    grouping_rule VARCHAR(64) NOT NULL,
    starts_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    ends_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY (id)
)
SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_closure_event_grouping_key ON closure_event (grouping_key)');
        $this->addSql('CREATE INDEX idx_closure_event_hospital_type_period ON closure_event (hospital_id, event_type, starts_at, ends_at)');
        $this->addSql('CREATE INDEX idx_closure_event_hospital_source_group ON closure_event (hospital_id, source_group_id) WHERE source_group_id IS NOT NULL');
        $this->addSql('ALTER TABLE closure_event ADD CONSTRAINT fk_closure_event_hospital FOREIGN KEY (hospital_id) REFERENCES hospital (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql(<<<'SQL'
CREATE TABLE closure_analysis_interval (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id BIGINT NOT NULL,
    hospital_id INT NOT NULL,
    speciality_id INT NOT NULL,
    department_id INT NOT NULL,
    starts_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    ends_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    reason VARCHAR(64) NOT NULL,
    facility_kind VARCHAR(32) NOT NULL,
    closure_unit VARCHAR(255) DEFAULT NULL,
    source_group_id VARCHAR(32) DEFAULT NULL,
    fingerprint VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
)
SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_closure_analysis_interval_fingerprint ON closure_analysis_interval (fingerprint)');
        $this->addSql('CREATE INDEX idx_closure_analysis_interval_event ON closure_analysis_interval (event_id)');
        $this->addSql('CREATE INDEX idx_closure_analysis_interval_department_period ON closure_analysis_interval (hospital_id, department_id, starts_at)');
        $this->addSql('CREATE INDEX idx_closure_analysis_interval_speciality_period ON closure_analysis_interval (hospital_id, speciality_id, starts_at)');
        $this->addSql('ALTER TABLE closure_analysis_interval ADD CONSTRAINT fk_closure_analysis_interval_event FOREIGN KEY (event_id) REFERENCES closure_event (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE closure_analysis_interval ADD CONSTRAINT fk_closure_analysis_interval_hospital FOREIGN KEY (hospital_id) REFERENCES hospital (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE closure_analysis_interval ADD CONSTRAINT fk_closure_analysis_interval_speciality FOREIGN KEY (speciality_id) REFERENCES speciality (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE closure_analysis_interval ADD CONSTRAINT fk_closure_analysis_interval_department FOREIGN KEY (department_id) REFERENCES department (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql(<<<'SQL'
CREATE TABLE closure_analysis_care_level (
    analysis_interval_id INT NOT NULL,
    care_level VARCHAR(32) NOT NULL,
    PRIMARY KEY (analysis_interval_id, care_level)
)
SQL);
        $this->addSql('ALTER TABLE closure_analysis_care_level ADD CONSTRAINT fk_closure_analysis_care_level_interval FOREIGN KEY (analysis_interval_id) REFERENCES closure_analysis_interval (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql(<<<'SQL'
CREATE TABLE closure_analysis_source (
    analysis_interval_id INT NOT NULL,
    closure_interval_id INT NOT NULL,
    import_id INT NOT NULL,
    PRIMARY KEY (analysis_interval_id, closure_interval_id)
)
SQL);
        $this->addSql('CREATE INDEX idx_closure_analysis_source_closure ON closure_analysis_source (closure_interval_id)');
        $this->addSql('CREATE INDEX idx_closure_analysis_source_import ON closure_analysis_source (import_id)');
        $this->addSql('ALTER TABLE closure_analysis_source ADD CONSTRAINT fk_closure_analysis_source_interval FOREIGN KEY (analysis_interval_id) REFERENCES closure_analysis_interval (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE closure_analysis_source ADD CONSTRAINT fk_closure_analysis_source_closure FOREIGN KEY (closure_interval_id) REFERENCES closure_interval (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE closure_analysis_source ADD CONSTRAINT fk_closure_analysis_source_import FOREIGN KEY (import_id) REFERENCES import (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql(<<<'SQL'
CREATE TABLE closure_relation_candidate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    hospital_id INT NOT NULL,
    analysis_interval_low_id INT NOT NULL,
    analysis_interval_high_id INT NOT NULL,
    kind VARCHAR(32) NOT NULL,
    PRIMARY KEY (id)
)
SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_closure_relation_candidate_pair ON closure_relation_candidate (analysis_interval_low_id, analysis_interval_high_id)');
        $this->addSql('CREATE INDEX idx_closure_relation_candidate_hospital ON closure_relation_candidate (hospital_id, kind)');
        $this->addSql('ALTER TABLE closure_relation_candidate ADD CONSTRAINT fk_closure_relation_candidate_low FOREIGN KEY (analysis_interval_low_id) REFERENCES closure_analysis_interval (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE closure_relation_candidate ADD CONSTRAINT fk_closure_relation_candidate_high FOREIGN KEY (analysis_interval_high_id) REFERENCES closure_analysis_interval (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql(<<<'SQL'
CREATE TABLE closure_rebuild_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    kind VARCHAR(16) NOT NULL,
    hospital_id INT DEFAULT NULL,
    requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    consumed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    PRIMARY KEY (id)
)
SQL);
        $this->addSql('CREATE INDEX idx_closure_rebuild_request_open ON closure_rebuild_request (kind, consumed_at)');

        $this->addSql('DROP TABLE IF EXISTS closure_volume_hour');
        $this->addSql(<<<'SQL'
CREATE TABLE closure_volume_hour (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id BIGINT NOT NULL,
    scope VARCHAR(16) NOT NULL,
    hospital_id INT NOT NULL,
    speciality_id INT NOT NULL,
    department_id INT NOT NULL,
    urgency_code SMALLINT NOT NULL,
    stratum VARCHAR(16) NOT NULL,
    bucket_start TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    bucket_end TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    in_closure BOOLEAN NOT NULL,
    observed_area NUMERIC(14, 4) DEFAULT NULL,
    expected_area NUMERIC(14, 4) DEFAULT NULL,
    observed_hospital NUMERIC(14, 4) DEFAULT NULL,
    expected_hospital NUMERIC(14, 4) DEFAULT NULL,
    evaluable_seconds INT NOT NULL,
    bucket_seconds INT NOT NULL,
    reference_slot_count INT NOT NULL,
    reference_assignment_count INT NOT NULL,
    reference_mode VARCHAR(32) NOT NULL,
    influenced BOOLEAN NOT NULL,
    quality VARCHAR(32) NOT NULL,
    reference_cutoff TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY (id)
)
SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_closure_volume_hour_grain ON closure_volume_hour (event_id, scope, speciality_id, department_id, urgency_code, stratum, bucket_start)');
        $this->addSql('CREATE INDEX idx_closure_volume_hour_population ON closure_volume_hour (hospital_id, scope, speciality_id, department_id, urgency_code, stratum, bucket_start)');
        $this->addSql('CREATE INDEX idx_closure_volume_hour_event ON closure_volume_hour (event_id, scope, stratum, in_closure, bucket_start)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS closure_volume_hour');
        $this->addSql(<<<'SQL'
CREATE TABLE closure_volume_hour (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    closure_interval_id INT NOT NULL,
    hospital_id INT NOT NULL,
    department_id INT NOT NULL,
    urgency_code SMALLINT NOT NULL,
    stratum VARCHAR(16) NOT NULL,
    bucket_start TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    bucket_end TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    in_closure BOOLEAN NOT NULL,
    observed_area NUMERIC(14, 4) DEFAULT NULL,
    expected_area NUMERIC(14, 4) DEFAULT NULL,
    observed_hospital NUMERIC(14, 4) DEFAULT NULL,
    expected_hospital NUMERIC(14, 4) DEFAULT NULL,
    evaluable_seconds INT NOT NULL,
    bucket_seconds INT NOT NULL,
    reference_slot_count INT NOT NULL,
    reference_assignment_count INT NOT NULL,
    reference_mode VARCHAR(32) NOT NULL,
    influenced BOOLEAN NOT NULL,
    quality VARCHAR(32) NOT NULL,
    reference_cutoff TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY (id)
)
SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_closure_volume_hour_grain ON closure_volume_hour (closure_interval_id, urgency_code, stratum, bucket_start)');
        $this->addSql('CREATE INDEX idx_closure_volume_hour_population ON closure_volume_hour (hospital_id, department_id, urgency_code, stratum, bucket_start)');
        $this->addSql('CREATE INDEX idx_closure_volume_hour_closure ON closure_volume_hour (closure_interval_id, stratum, in_closure, bucket_start)');
        $this->addSql('DROP TABLE closure_rebuild_request');
        $this->addSql('DROP TABLE closure_relation_candidate');
        $this->addSql('DROP TABLE closure_analysis_source');
        $this->addSql('DROP TABLE closure_analysis_care_level');
        $this->addSql('DROP TABLE closure_analysis_interval');
        $this->addSql('DROP TABLE closure_event');
        $this->addSql('ALTER TABLE import DROP export_starts_at');
        $this->addSql('ALTER TABLE import DROP export_ends_at');
    }
}
