<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261004173624 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add the closure volume hour projection.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
CREATE TABLE closure_volume_hour (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    closure_interval_id INT NOT NULL,
    hospital_id INT NOT NULL,
    department_id INT NOT NULL,
    urgency_code SMALLINT NOT NULL,
    stratum VARCHAR(16) NOT NULL,
    bucket_start TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    bucket_end TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    in_closure BOOLEAN NOT NULL,
    observed_area NUMERIC(14, 4) DEFAULT NULL,
    expected_area NUMERIC(14, 4) DEFAULT NULL,
    observed_hospital NUMERIC(14, 4) DEFAULT NULL,
    expected_hospital NUMERIC(14, 4) DEFAULT NULL,
    evaluable_seconds INT NOT NULL,
    bucket_seconds INT NOT NULL,
    reference_slot_count INT NOT NULL,
    reference_assignment_count INT NOT NULL,
    reference_mode VARCHAR(32) NOT NULL,
    influenced BOOLEAN NOT NULL,
    quality VARCHAR(32) NOT NULL,
    reference_cutoff TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY (id)
)
SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_closure_volume_hour_grain ON closure_volume_hour (closure_interval_id, urgency_code, stratum, bucket_start)');
        $this->addSql('CREATE INDEX idx_closure_volume_hour_population ON closure_volume_hour (hospital_id, department_id, urgency_code, stratum, bucket_start)');
        $this->addSql('CREATE INDEX idx_closure_volume_hour_closure ON closure_volume_hour (closure_interval_id, stratum, in_closure, bucket_start)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE closure_volume_hour');
    }
}
