<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250819090129 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE import (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, file_path VARCHAR(255) NOT NULL, file_extension VARCHAR(255) NOT NULL, file_mime_type VARCHAR(255) NOT NULL, file_size INT NOT NULL, row_count INT NOT NULL, run_count INT NOT NULL, run_time INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, hospital_id INT NOT NULL, created_by_id INT NOT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9D4ECE1D63DBB69 ON import (hospital_id)');
        $this->addSql('CREATE INDEX IDX_9D4ECE1DB03A8386 ON import (created_by_id)');
        $this->addSql('CREATE INDEX IDX_9D4ECE1D896DBBDE ON import (updated_by_id)');
        $this->addSql('ALTER TABLE import ADD CONSTRAINT FK_9D4ECE1D63DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE import ADD CONSTRAINT FK_9D4ECE1DB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE import ADD CONSTRAINT FK_9D4ECE1D896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE import DROP CONSTRAINT FK_9D4ECE1D63DBB69');
        $this->addSql('ALTER TABLE import DROP CONSTRAINT FK_9D4ECE1DB03A8386');
        $this->addSql('ALTER TABLE import DROP CONSTRAINT FK_9D4ECE1D896DBBDE');
        $this->addSql('DROP TABLE import');
    }
}
