<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260409143036 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add cookie_consent table for GDPR consent preferences.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE cookie_consent (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT DEFAULT NULL, subject_id VARCHAR(64) NOT NULL, consent_version VARCHAR(16) NOT NULL, preferences JSON NOT NULL, decided_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_cookie_consent_subject ON cookie_consent (subject_id)');
        $this->addSql('CREATE INDEX idx_cookie_consent_user ON cookie_consent (user_id)');
        $this->addSql('ALTER TABLE cookie_consent ADD CONSTRAINT FK_6C0219BCA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE cookie_consent DROP CONSTRAINT FK_6C0219BCA76ED395');
        $this->addSql('DROP TABLE cookie_consent');
    }
}
