<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250916083501 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE indication_normalized (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code INT NOT NULL, name VARCHAR(255) NOT NULL, note VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by_id INT NOT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B3197597B03A8386 ON indication_normalized (created_by_id)');
        $this->addSql('CREATE INDEX IDX_B3197597896DBBDE ON indication_normalized (updated_by_id)');
        $this->addSql('CREATE TABLE indication_raw (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code INT NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by_id INT NOT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E928F552B03A8386 ON indication_raw (created_by_id)');
        $this->addSql('CREATE INDEX IDX_E928F552896DBBDE ON indication_raw (updated_by_id)');
        $this->addSql('ALTER TABLE indication_normalized ADD CONSTRAINT FK_B3197597B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE indication_normalized ADD CONSTRAINT FK_B3197597896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE indication_raw ADD CONSTRAINT FK_E928F552B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE indication_raw ADD CONSTRAINT FK_E928F552896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE allocation ADD indication_raw_id INT NOT NULL');
        $this->addSql('ALTER TABLE allocation ADD indication_normalized_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE allocation ADD CONSTRAINT FK_5C44232A55078205 FOREIGN KEY (indication_raw_id) REFERENCES indication_raw (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE allocation ADD CONSTRAINT FK_5C44232AA83E4E85 FOREIGN KEY (indication_normalized_id) REFERENCES indication_normalized (id)');
        $this->addSql('CREATE INDEX IDX_5C44232A55078205 ON allocation (indication_raw_id)');
        $this->addSql('CREATE INDEX IDX_5C44232AA83E4E85 ON allocation (indication_normalized_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE indication_normalized DROP CONSTRAINT FK_B3197597B03A8386');
        $this->addSql('ALTER TABLE indication_normalized DROP CONSTRAINT FK_B3197597896DBBDE');
        $this->addSql('ALTER TABLE indication_raw DROP CONSTRAINT FK_E928F552B03A8386');
        $this->addSql('ALTER TABLE indication_raw DROP CONSTRAINT FK_E928F552896DBBDE');
        $this->addSql('DROP TABLE indication_normalized');
        $this->addSql('DROP TABLE indication_raw');
        $this->addSql('ALTER TABLE allocation DROP CONSTRAINT FK_5C44232A55078205');
        $this->addSql('ALTER TABLE allocation DROP CONSTRAINT FK_5C44232AA83E4E85');
        $this->addSql('DROP INDEX IDX_5C44232A55078205');
        $this->addSql('DROP INDEX IDX_5C44232AA83E4E85');
        $this->addSql('ALTER TABLE allocation DROP indication_raw_id');
        $this->addSql('ALTER TABLE allocation DROP indication_normalized_id');
    }
}
