<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251128090429 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add Assessment to Allocations';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE assessment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, airway VARCHAR(255) NOT NULL, breathing VARCHAR(255) NOT NULL, circulation VARCHAR(255) NOT NULL, disability VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE allocation ADD assessment_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE allocation ADD CONSTRAINT FK_5C44232ADD3DD5F1 FOREIGN KEY (assessment_id) REFERENCES assessment (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5C44232ADD3DD5F1 ON allocation (assessment_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE assessment');
        $this->addSql('ALTER TABLE allocation DROP CONSTRAINT FK_5C44232ADD3DD5F1');
        $this->addSql('DROP INDEX UNIQ_5C44232ADD3DD5F1');
        $this->addSql('ALTER TABLE allocation DROP assessment_id');
    }
}
