<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261001120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add department and speciality alias tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE department_alias (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, department_id INT NOT NULL, name VARCHAR(255) NOT NULL, normalized_name VARCHAR(255) NOT NULL, classification VARCHAR(64) NOT NULL, source VARCHAR(64) NOT NULL, valid_from DATE DEFAULT NULL, valid_to DATE DEFAULT NULL, note TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_department_alias_normalized_name ON department_alias (normalized_name)');
        $this->addSql('CREATE INDEX IDX_DEPARTMENT_ALIAS_DEPARTMENT ON department_alias (department_id)');
        $this->addSql('ALTER TABLE department_alias ADD CONSTRAINT FK_DEPARTMENT_ALIAS_DEPARTMENT FOREIGN KEY (department_id) REFERENCES department (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('CREATE TABLE speciality_alias (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, speciality_id INT NOT NULL, name VARCHAR(255) NOT NULL, normalized_name VARCHAR(255) NOT NULL, classification VARCHAR(64) NOT NULL, source VARCHAR(64) NOT NULL, valid_from DATE DEFAULT NULL, valid_to DATE DEFAULT NULL, note TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_speciality_alias_normalized_name ON speciality_alias (normalized_name)');
        $this->addSql('CREATE INDEX IDX_SPECIALITY_ALIAS_SPECIALITY ON speciality_alias (speciality_id)');
        $this->addSql('ALTER TABLE speciality_alias ADD CONSTRAINT FK_SPECIALITY_ALIAS_SPECIALITY FOREIGN KEY (speciality_id) REFERENCES speciality (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE department_alias DROP CONSTRAINT FK_DEPARTMENT_ALIAS_DEPARTMENT');
        $this->addSql('DROP TABLE department_alias');
        $this->addSql('ALTER TABLE speciality_alias DROP CONSTRAINT FK_SPECIALITY_ALIAS_SPECIALITY');
        $this->addSql('DROP TABLE speciality_alias');
    }
}
