<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260327153105 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add audit_log table for domain audit trail.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE audit_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, request_id VARCHAR(128) NOT NULL, actor_id INT DEFAULT NULL, origin VARCHAR(32) NOT NULL, action VARCHAR(16) NOT NULL, entity_class VARCHAR(255) NOT NULL, entity_id VARCHAR(64) DEFAULT NULL, changes JSON NOT NULL, metadata JSON DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_audit_log_request ON audit_log (request_id)');
        $this->addSql('CREATE INDEX IDX_audit_log_entity ON audit_log (entity_class, entity_id)');
        $this->addSql('CREATE INDEX IDX_audit_log_actor ON audit_log (actor_id)');
        $this->addSql('ALTER TABLE audit_log ADD CONSTRAINT FK_audit_log_actor FOREIGN KEY (actor_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE audit_log DROP CONSTRAINT FK_audit_log_actor');
        $this->addSql('DROP TABLE audit_log');
    }
}
