<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260510190000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Alpha feedback submissions (guest or authenticated)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE feedback (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, category VARCHAR(255) NOT NULL, message TEXT NOT NULL, guest_email VARCHAR(180) DEFAULT NULL, page_url VARCHAR(2048) NOT NULL, route_name VARCHAR(255) DEFAULT NULL, context JSON DEFAULT NULL, user_agent TEXT DEFAULT NULL, app_version VARCHAR(64) DEFAULT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, submitted_by_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D2294458CC9E6E10 ON feedback (submitted_by_id)');
        $this->addSql('ALTER TABLE feedback ADD CONSTRAINT FK_D2294458CC9E6E10 FOREIGN KEY (submitted_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE feedback DROP CONSTRAINT FK_D2294458CC9E6E10');
        $this->addSql('DROP TABLE feedback');
    }
}
