<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260929194500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add generic per-user DataTable preferences';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE data_table_preference (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, table_key VARCHAR(120) NOT NULL, configuration JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_data_table_preference_user_key ON data_table_preference (user_id, table_key)');
        $this->addSql('CREATE INDEX IDX_DATA_TABLE_PREFERENCE_USER ON data_table_preference (user_id)');
        $this->addSql('ALTER TABLE data_table_preference ADD CONSTRAINT FK_DATA_TABLE_PREFERENCE_USER FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE data_table_preference DROP CONSTRAINT FK_DATA_TABLE_PREFERENCE_USER');
        $this->addSql('DROP TABLE data_table_preference');
    }
}
