<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260811121949 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add page_translation table for locale-specific CMS page content (additive; legacy page columns retained)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE page_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, page_id INT NOT NULL, locale VARCHAR(8) NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(180) NOT NULL, path VARCHAR(500) NOT NULL, status VARCHAR(32) NOT NULL, content JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A0A4C2DDC4663E4 ON page_translation (page_id)');
        $this->addSql('CREATE INDEX idx_page_translation_locale_status ON page_translation (locale, status)');
        $this->addSql('CREATE UNIQUE INDEX uniq_page_translation_page_locale ON page_translation (page_id, locale)');
        $this->addSql('CREATE UNIQUE INDEX uniq_page_translation_path ON page_translation (path)');
        $this->addSql('ALTER TABLE page_translation ADD CONSTRAINT FK_A0A4C2DDC4663E4 FOREIGN KEY (page_id) REFERENCES page (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE page_translation DROP CONSTRAINT FK_A0A4C2DDC4663E4');
        $this->addSql('DROP TABLE page_translation');
    }
}
