<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260908072833 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create daily analytics aggregate tables and aggregation-run marker for 30-day raw retention.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE analytics_aggregation_run (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                date DATE NOT NULL,
                aggregated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                raw_request_count INT NOT NULL,
                raw_event_count INT NOT NULL,
                aggregate_rows_written INT NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_analytics_aggregation_run_date ON analytics_aggregation_run (date)');

        $this->addSql(<<<'SQL'
            CREATE TABLE analytics_request_daily (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                date DATE NOT NULL,
                feature_area VARCHAR(32) NOT NULL,
                route_name VARCHAR(180) DEFAULT NULL,
                is_authenticated BOOLEAN NOT NULL,
                user_role VARCHAR(64) DEFAULT NULL,
                request_count INT NOT NULL,
                error_count INT NOT NULL,
                sum_duration_ms INT NOT NULL,
                sum_db_query_count INT NOT NULL,
                sum_db_time_ms INT NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_analytics_request_daily_date ON analytics_request_daily (date)');
        $this->addSql('CREATE UNIQUE INDEX uniq_analytics_request_daily_grain ON analytics_request_daily (date, feature_area, route_name, is_authenticated, user_role) NULLS NOT DISTINCT');

        $this->addSql(<<<'SQL'
            CREATE TABLE analytics_event_daily (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                date DATE NOT NULL,
                event_name VARCHAR(120) NOT NULL,
                feature_area VARCHAR(32) DEFAULT NULL,
                user_role VARCHAR(64) NOT NULL,
                event_count INT NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_analytics_event_daily_date ON analytics_event_daily (date)');
        $this->addSql('CREATE UNIQUE INDEX uniq_analytics_event_daily_grain ON analytics_event_daily (date, event_name, feature_area, user_role) NULLS NOT DISTINCT');

        $this->addSql(<<<'SQL'
            CREATE TABLE analytics_filter_param_daily (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                date DATE NOT NULL,
                param_name VARCHAR(255) NOT NULL,
                usage_count INT NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_analytics_filter_param_daily_date ON analytics_filter_param_daily (date)');
        $this->addSql('CREATE UNIQUE INDEX uniq_analytics_filter_param_daily ON analytics_filter_param_daily (date, param_name)');

        $this->addSql(<<<'SQL'
            CREATE TABLE analytics_filter_area_daily (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                date DATE NOT NULL,
                feature_area VARCHAR(32) NOT NULL,
                with_filters INT NOT NULL,
                without_filters INT NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_analytics_filter_area_daily_date ON analytics_filter_area_daily (date)');
        $this->addSql('CREATE UNIQUE INDEX uniq_analytics_filter_area_daily ON analytics_filter_area_daily (date, feature_area)');

        $this->addSql(<<<'SQL'
            CREATE TABLE analytics_transition_daily (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                date DATE NOT NULL,
                from_route VARCHAR(180) NOT NULL,
                to_route VARCHAR(180) NOT NULL,
                transition_count INT NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_analytics_transition_daily_date ON analytics_transition_daily (date)');
        $this->addSql('CREATE UNIQUE INDEX uniq_analytics_transition_daily ON analytics_transition_daily (date, from_route, to_route)');

        $this->addSql(<<<'SQL'
            CREATE TABLE analytics_session_boundary_daily (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                date DATE NOT NULL,
                route_name VARCHAR(180) NOT NULL,
                kind VARCHAR(8) NOT NULL,
                session_count INT NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_analytics_session_boundary_daily_date ON analytics_session_boundary_daily (date)');
        $this->addSql('CREATE UNIQUE INDEX uniq_analytics_session_boundary_daily ON analytics_session_boundary_daily (date, route_name, kind)');

        $this->addSql(<<<'SQL'
            CREATE TABLE analytics_uniques_daily (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                date DATE NOT NULL,
                dau INT NOT NULL,
                distinct_visitors INT NOT NULL,
                distinct_sessions INT NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_analytics_uniques_daily_date ON analytics_uniques_daily (date)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE analytics_uniques_daily');
        $this->addSql('DROP TABLE analytics_session_boundary_daily');
        $this->addSql('DROP TABLE analytics_transition_daily');
        $this->addSql('DROP TABLE analytics_filter_area_daily');
        $this->addSql('DROP TABLE analytics_filter_param_daily');
        $this->addSql('DROP TABLE analytics_event_daily');
        $this->addSql('DROP TABLE analytics_request_daily');
        $this->addSql('DROP TABLE analytics_aggregation_run');
    }
}
