<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260621162543 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add saved_explorer_view table for Analysis Explorer V2 saved views.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE saved_explorer_view (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(120) NOT NULL, title VARCHAR(180) NOT NULL, description TEXT DEFAULT NULL, category VARCHAR(80) NOT NULL, config_json JSON NOT NULL, is_system BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_saved_explorer_view_slug ON saved_explorer_view (slug)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE saved_explorer_view');
    }
}
