<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250814173421 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE allocation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, arrival_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, requires_resus BOOLEAN NOT NULL, requires_cathlab BOOLEAN NOT NULL, gender VARCHAR(1) NOT NULL, is_cpr BOOLEAN NOT NULL, is_ventilated BOOLEAN NOT NULL, is_shock BOOLEAN NOT NULL, is_pregnant BOOLEAN NOT NULL, is_with_physician BOOLEAN NOT NULL, hospital_id INT NOT NULL, dispatch_area_id INT NOT NULL, state_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5C44232A63DBB69 ON allocation (hospital_id)');
        $this->addSql('CREATE INDEX IDX_5C44232A957FD192 ON allocation (dispatch_area_id)');
        $this->addSql('CREATE INDEX IDX_5C44232A5D83CC1 ON allocation (state_id)');
        $this->addSql('ALTER TABLE allocation ADD CONSTRAINT FK_5C44232A63DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE allocation ADD CONSTRAINT FK_5C44232A957FD192 FOREIGN KEY (dispatch_area_id) REFERENCES dispatch_area (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE allocation ADD CONSTRAINT FK_5C44232A5D83CC1 FOREIGN KEY (state_id) REFERENCES state (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE allocation DROP CONSTRAINT FK_5C44232A63DBB69');
        $this->addSql('ALTER TABLE allocation DROP CONSTRAINT FK_5C44232A957FD192');
        $this->addSql('ALTER TABLE allocation DROP CONSTRAINT FK_5C44232A5D83CC1');
        $this->addSql('DROP TABLE allocation');
    }
}
