<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250914125233 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE assignment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by_id INT NOT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_30C544BAB03A8386 ON assignment (created_by_id)');
        $this->addSql('CREATE INDEX IDX_30C544BA896DBBDE ON assignment (updated_by_id)');
        $this->addSql('CREATE TABLE infection (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by_id INT NOT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_56518720B03A8386 ON infection (created_by_id)');
        $this->addSql('CREATE INDEX IDX_56518720896DBBDE ON infection (updated_by_id)');
        $this->addSql('CREATE TABLE occasion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by_id INT NOT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8A66DCE5B03A8386 ON occasion (created_by_id)');
        $this->addSql('CREATE INDEX IDX_8A66DCE5896DBBDE ON occasion (updated_by_id)');
        $this->addSql('ALTER TABLE assignment ADD CONSTRAINT FK_30C544BAB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE assignment ADD CONSTRAINT FK_30C544BA896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE infection ADD CONSTRAINT FK_56518720B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE infection ADD CONSTRAINT FK_56518720896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE occasion ADD CONSTRAINT FK_8A66DCE5B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE occasion ADD CONSTRAINT FK_8A66DCE5896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE allocation ADD occasion_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE allocation ADD assignment_id INT NOT NULL');
        $this->addSql('ALTER TABLE allocation ADD infection_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE allocation ADD CONSTRAINT FK_5C44232A4034998F FOREIGN KEY (occasion_id) REFERENCES occasion (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE allocation ADD CONSTRAINT FK_5C44232AD19302F8 FOREIGN KEY (assignment_id) REFERENCES assignment (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE allocation ADD CONSTRAINT FK_5C44232A36A2EC68 FOREIGN KEY (infection_id) REFERENCES infection (id)');
        $this->addSql('CREATE INDEX IDX_5C44232A4034998F ON allocation (occasion_id)');
        $this->addSql('CREATE INDEX IDX_5C44232AD19302F8 ON allocation (assignment_id)');
        $this->addSql('CREATE INDEX IDX_5C44232A36A2EC68 ON allocation (infection_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE assignment DROP CONSTRAINT FK_30C544BAB03A8386');
        $this->addSql('ALTER TABLE assignment DROP CONSTRAINT FK_30C544BA896DBBDE');
        $this->addSql('ALTER TABLE infection DROP CONSTRAINT FK_56518720B03A8386');
        $this->addSql('ALTER TABLE infection DROP CONSTRAINT FK_56518720896DBBDE');
        $this->addSql('ALTER TABLE occasion DROP CONSTRAINT FK_8A66DCE5B03A8386');
        $this->addSql('ALTER TABLE occasion DROP CONSTRAINT FK_8A66DCE5896DBBDE');
        $this->addSql('DROP TABLE assignment');
        $this->addSql('DROP TABLE infection');
        $this->addSql('DROP TABLE occasion');
        $this->addSql('ALTER TABLE allocation DROP CONSTRAINT FK_5C44232A4034998F');
        $this->addSql('ALTER TABLE allocation DROP CONSTRAINT FK_5C44232AD19302F8');
        $this->addSql('ALTER TABLE allocation DROP CONSTRAINT FK_5C44232A36A2EC68');
        $this->addSql('DROP INDEX IDX_5C44232A4034998F');
        $this->addSql('DROP INDEX IDX_5C44232AD19302F8');
        $this->addSql('DROP INDEX IDX_5C44232A36A2EC68');
        $this->addSql('ALTER TABLE allocation DROP occasion_id');
        $this->addSql('ALTER TABLE allocation DROP assignment_id');
        $this->addSql('ALTER TABLE allocation DROP infection_id');
    }
}
