<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250811142045 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE hospital (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, location VARCHAR(255) NOT NULL, tier VARCHAR(255) NOT NULL, size VARCHAR(255) NOT NULL, beds INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, address_street VARCHAR(255) NOT NULL, address_postal_code VARCHAR(255) NOT NULL, address_city VARCHAR(255) NOT NULL, address_state VARCHAR(255) NOT NULL, address_country VARCHAR(255) NOT NULL, owner_id INT DEFAULT NULL, dispatch_area_id INT NOT NULL, state_id INT NOT NULL, created_by_id INT NOT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4282C85B7E3C61F9 ON hospital (owner_id)');
        $this->addSql('CREATE INDEX IDX_4282C85B957FD192 ON hospital (dispatch_area_id)');
        $this->addSql('CREATE INDEX IDX_4282C85B5D83CC1 ON hospital (state_id)');
        $this->addSql('CREATE INDEX IDX_4282C85BB03A8386 ON hospital (created_by_id)');
        $this->addSql('CREATE INDEX IDX_4282C85B896DBBDE ON hospital (updated_by_id)');
        $this->addSql('ALTER TABLE hospital ADD CONSTRAINT FK_4282C85B7E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE hospital ADD CONSTRAINT FK_4282C85B957FD192 FOREIGN KEY (dispatch_area_id) REFERENCES dispatch_area (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE hospital ADD CONSTRAINT FK_4282C85B5D83CC1 FOREIGN KEY (state_id) REFERENCES state (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE hospital ADD CONSTRAINT FK_4282C85BB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE hospital ADD CONSTRAINT FK_4282C85B896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dispatch_area ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE dispatch_area ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN dispatch_area.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN dispatch_area.updated_at IS \'\'');
        $this->addSql('ALTER TABLE state ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE state ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN state.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN state.updated_at IS \'\'');
        $this->addSql('ALTER TABLE "user" ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE "user" ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE messenger_messages ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'\'');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE hospital DROP CONSTRAINT FK_4282C85B7E3C61F9');
        $this->addSql('ALTER TABLE hospital DROP CONSTRAINT FK_4282C85B957FD192');
        $this->addSql('ALTER TABLE hospital DROP CONSTRAINT FK_4282C85B5D83CC1');
        $this->addSql('ALTER TABLE hospital DROP CONSTRAINT FK_4282C85BB03A8386');
        $this->addSql('ALTER TABLE hospital DROP CONSTRAINT FK_4282C85B896DBBDE');
        $this->addSql('DROP TABLE hospital');
        $this->addSql('ALTER TABLE dispatch_area ALTER id SET DEFAULT nextval(\'dispatch_area_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE dispatch_area ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN dispatch_area.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN dispatch_area.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE messenger_messages ALTER id SET DEFAULT nextval(\'messenger_messages_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE state ALTER id SET DEFAULT nextval(\'state_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE state ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN state.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN state.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE "user" ALTER id SET DEFAULT nextval(\'user_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE "user" ALTER id DROP IDENTITY');
    }
}
