<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260602124432 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create media table for uploaded images and PDFs';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE media (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, filename VARCHAR(255) DEFAULT NULL, original_filename VARCHAR(255) DEFAULT NULL, mime_type VARCHAR(128) DEFAULT NULL, size INT DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, alt_text VARCHAR(255) DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6A2CA10CB03A8386 ON media (created_by_id)');
        $this->addSql('CREATE INDEX IDX_6A2CA10C896DBBDE ON media (updated_by_id)');
        $this->addSql('ALTER TABLE media ADD CONSTRAINT FK_6A2CA10CB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE media ADD CONSTRAINT FK_6A2CA10C896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE media DROP CONSTRAINT FK_6A2CA10CB03A8386');
        $this->addSql('ALTER TABLE media DROP CONSTRAINT FK_6A2CA10C896DBBDE');
        $this->addSql('DROP TABLE media');
    }
}
