<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260814094512 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add user_activity projection table for profile activity feed.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE user_activity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, type VARCHAR(64) NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deduplication_key VARCHAR(191) NOT NULL, metadata JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_activity_deduplication_key ON user_activity (deduplication_key)');
        $this->addSql('CREATE INDEX idx_user_activity_feed ON user_activity (user_id, occurred_at DESC, id DESC)');
        $this->addSql('ALTER TABLE user_activity ADD CONSTRAINT FK_USER_ACTIVITY_USER FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE user_activity DROP CONSTRAINT FK_USER_ACTIVITY_USER');
        $this->addSql('DROP TABLE user_activity');
    }
}
