<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Manual migration for new MCI case storage.
 */
final class Version20260319112133 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create mci_case table for mass casualty incidents';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE mci_case (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, arrival_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, gender VARCHAR(1) DEFAULT NULL, age INT DEFAULT NULL, requires_resus BOOLEAN DEFAULT NULL, requires_cathlab BOOLEAN DEFAULT NULL, is_cpr BOOLEAN DEFAULT NULL, is_ventilated BOOLEAN DEFAULT NULL, is_shock BOOLEAN DEFAULT NULL, is_pregnant BOOLEAN DEFAULT NULL, is_with_physician BOOLEAN DEFAULT NULL, transport_type VARCHAR(255) DEFAULT NULL, urgency INT DEFAULT NULL, speciality_id INT DEFAULT NULL, department_id INT DEFAULT NULL, department_was_closed BOOLEAN DEFAULT NULL, occasion_id INT DEFAULT NULL, infection_id INT DEFAULT NULL, indication_raw_id INT DEFAULT NULL, indication_normalized_id INT DEFAULT NULL, mci_id VARCHAR(255) NOT NULL, mci_title VARCHAR(255) NOT NULL, hospital_id INT NOT NULL, dispatch_area_id INT NOT NULL, state_id INT NOT NULL, import_id INT NOT NULL, PRIMARY KEY (id))');

        $this->addSql('CREATE INDEX IDX_mci_case_hospital_id ON mci_case (hospital_id)');
        $this->addSql('CREATE INDEX IDX_mci_case_dispatch_area_id ON mci_case (dispatch_area_id)');
        $this->addSql('CREATE INDEX IDX_mci_case_state_id ON mci_case (state_id)');
        $this->addSql('CREATE INDEX IDX_mci_case_import_id ON mci_case (import_id)');

        $this->addSql('CREATE INDEX IDX_mci_case_speciality_id ON mci_case (speciality_id)');
        $this->addSql('CREATE INDEX IDX_mci_case_department_id ON mci_case (department_id)');
        $this->addSql('CREATE INDEX IDX_mci_case_occasion_id ON mci_case (occasion_id)');
        $this->addSql('CREATE INDEX IDX_mci_case_infection_id ON mci_case (infection_id)');
        $this->addSql('CREATE INDEX IDX_mci_case_indication_raw_id ON mci_case (indication_raw_id)');
        $this->addSql('CREATE INDEX IDX_mci_case_indication_normalized_id ON mci_case (indication_normalized_id)');

        $this->addSql('ALTER TABLE mci_case ADD CONSTRAINT FK_mci_case_hospital FOREIGN KEY (hospital_id) REFERENCES hospital (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mci_case ADD CONSTRAINT FK_mci_case_dispatch_area FOREIGN KEY (dispatch_area_id) REFERENCES dispatch_area (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mci_case ADD CONSTRAINT FK_mci_case_state FOREIGN KEY (state_id) REFERENCES state (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mci_case ADD CONSTRAINT FK_mci_case_import FOREIGN KEY (import_id) REFERENCES import (id) NOT DEFERRABLE');

        $this->addSql('ALTER TABLE mci_case ADD CONSTRAINT FK_mci_case_speciality FOREIGN KEY (speciality_id) REFERENCES speciality (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mci_case ADD CONSTRAINT FK_mci_case_department FOREIGN KEY (department_id) REFERENCES department (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mci_case ADD CONSTRAINT FK_mci_case_occasion FOREIGN KEY (occasion_id) REFERENCES occasion (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mci_case ADD CONSTRAINT FK_mci_case_infection FOREIGN KEY (infection_id) REFERENCES infection (id)');
        $this->addSql('ALTER TABLE mci_case ADD CONSTRAINT FK_mci_case_indication_raw FOREIGN KEY (indication_raw_id) REFERENCES indication_raw (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mci_case ADD CONSTRAINT FK_mci_case_indication_normalized FOREIGN KEY (indication_normalized_id) REFERENCES indication_normalized (id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE mci_case DROP CONSTRAINT FK_mci_case_indication_normalized');
        $this->addSql('ALTER TABLE mci_case DROP CONSTRAINT FK_mci_case_indication_raw');
        $this->addSql('ALTER TABLE mci_case DROP CONSTRAINT FK_mci_case_infection');
        $this->addSql('ALTER TABLE mci_case DROP CONSTRAINT FK_mci_case_occasion');
        $this->addSql('ALTER TABLE mci_case DROP CONSTRAINT FK_mci_case_department');
        $this->addSql('ALTER TABLE mci_case DROP CONSTRAINT FK_mci_case_speciality');
        $this->addSql('ALTER TABLE mci_case DROP CONSTRAINT FK_mci_case_import');
        $this->addSql('ALTER TABLE mci_case DROP CONSTRAINT FK_mci_case_state');
        $this->addSql('ALTER TABLE mci_case DROP CONSTRAINT FK_mci_case_dispatch_area');
        $this->addSql('ALTER TABLE mci_case DROP CONSTRAINT FK_mci_case_hospital');

        $this->addSql('DROP INDEX IDX_mci_case_indication_normalized_id');
        $this->addSql('DROP INDEX IDX_mci_case_indication_raw_id');
        $this->addSql('DROP INDEX IDX_mci_case_infection_id');
        $this->addSql('DROP INDEX IDX_mci_case_occasion_id');
        $this->addSql('DROP INDEX IDX_mci_case_department_id');
        $this->addSql('DROP INDEX IDX_mci_case_speciality_id');
        $this->addSql('DROP INDEX IDX_mci_case_import_id');
        $this->addSql('DROP INDEX IDX_mci_case_state_id');
        $this->addSql('DROP INDEX IDX_mci_case_dispatch_area_id');
        $this->addSql('DROP INDEX IDX_mci_case_hospital_id');

        $this->addSql('DROP TABLE mci_case');
    }
}
