<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260928091656 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add closure intervals imported from IVENA closure lists.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE closure_interval (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, care_level VARCHAR(32) NOT NULL, reason VARCHAR(64) NOT NULL, facility_kind VARCHAR(32) NOT NULL, closure_unit VARCHAR(255) DEFAULT NULL, source_group_id VARCHAR(32) DEFAULT NULL, remark TEXT DEFAULT NULL, internal_remark TEXT DEFAULT NULL, source_recorded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, source_changed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, hospital_id INT NOT NULL, import_id INT NOT NULL, speciality_id INT NOT NULL, department_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_closure_interval_hospital_unit ON closure_interval (hospital_id, closure_unit)');
        $this->addSql('CREATE INDEX idx_closure_interval_source_group ON closure_interval (source_group_id)');
        $this->addSql('CREATE INDEX idx_closure_interval_import ON closure_interval (import_id)');
        $this->addSql('CREATE INDEX idx_closure_interval_speciality ON closure_interval (speciality_id)');
        $this->addSql('CREATE INDEX idx_closure_interval_department ON closure_interval (department_id)');
        $this->addSql('ALTER TABLE closure_interval ADD CONSTRAINT fk_closure_interval_hospital FOREIGN KEY (hospital_id) REFERENCES hospital (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE closure_interval ADD CONSTRAINT fk_closure_interval_import FOREIGN KEY (import_id) REFERENCES import (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE closure_interval ADD CONSTRAINT fk_closure_interval_speciality FOREIGN KEY (speciality_id) REFERENCES speciality (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE closure_interval ADD CONSTRAINT fk_closure_interval_department FOREIGN KEY (department_id) REFERENCES department (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE closure_interval DROP CONSTRAINT fk_closure_interval_hospital');
        $this->addSql('ALTER TABLE closure_interval DROP CONSTRAINT fk_closure_interval_import');
        $this->addSql('ALTER TABLE closure_interval DROP CONSTRAINT fk_closure_interval_speciality');
        $this->addSql('ALTER TABLE closure_interval DROP CONSTRAINT fk_closure_interval_department');
        $this->addSql('DROP TABLE closure_interval');
    }
}
