<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251204215511 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add new ImportReject entity';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE import_reject (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, line_number INT DEFAULT NULL, messages JSON NOT NULL, row JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, import_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D9F4DCA1B6A263D9 ON import_reject (import_id)');
        $this->addSql('ALTER TABLE import_reject ADD CONSTRAINT FK_D9F4DCA1B6A263D9 FOREIGN KEY (import_id) REFERENCES import (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE import_reject DROP CONSTRAINT FK_D9F4DCA1B6A263D9');
        $this->addSql('DROP TABLE import_reject');
    }
}
