<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260804151958 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create analytics_request and analytics_product_event tables for usage analytics MVP.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE analytics_request (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                route_name VARCHAR(180) DEFAULT NULL,
                feature_area VARCHAR(32) NOT NULL,
                http_status INT NOT NULL,
                duration_ms INT NOT NULL,
                db_query_count INT NOT NULL,
                db_time_ms INT NOT NULL,
                is_authenticated BOOLEAN NOT NULL,
                user_role VARCHAR(64) DEFAULT NULL,
                analytics_user_key VARCHAR(64) DEFAULT NULL,
                visitor_key VARCHAR(36) DEFAULT NULL,
                session_key VARCHAR(36) DEFAULT NULL,
                browser_family VARCHAR(16) NOT NULL,
                device_type VARCHAR(16) NOT NULL,
                query_param_names JSON NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_analytics_request_occurred_at ON analytics_request (occurred_at)');
        $this->addSql('CREATE INDEX idx_analytics_request_route_name ON analytics_request (route_name)');
        $this->addSql('CREATE INDEX idx_analytics_request_feature_area ON analytics_request (feature_area)');
        $this->addSql('CREATE INDEX idx_analytics_request_occurred_feature ON analytics_request (occurred_at, feature_area)');

        $this->addSql(<<<'SQL'
            CREATE TABLE analytics_product_event (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                event_name VARCHAR(120) NOT NULL,
                feature_area VARCHAR(32) DEFAULT NULL,
                analytics_user_key VARCHAR(64) DEFAULT NULL,
                visitor_key VARCHAR(36) DEFAULT NULL,
                session_key VARCHAR(36) DEFAULT NULL,
                context JSON NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_analytics_product_event_occurred_at ON analytics_product_event (occurred_at)');
        $this->addSql('CREATE INDEX idx_analytics_product_event_name ON analytics_product_event (event_name)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE analytics_product_event');
        $this->addSql('DROP TABLE analytics_request');
    }
}
