<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260603145125 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create kpi_daily table for aggregated admin dashboard KPIs.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE kpi_daily (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, imports_count INT NOT NULL, successful_imports_count INT NOT NULL, records_total INT NOT NULL, records_processed INT NOT NULL, records_rejected INT NOT NULL, failed_imports_count INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, hospital_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_kpi_daily_date ON kpi_daily (date)');
        $this->addSql('CREATE INDEX idx_kpi_daily_hospital_date ON kpi_daily (hospital_id, date)');
        $this->addSql('CREATE UNIQUE INDEX uniq_kpi_daily_date_hospital ON kpi_daily (date, hospital_id) NULLS NOT DISTINCT');
        $this->addSql('ALTER TABLE kpi_daily ADD CONSTRAINT FK_KPI_DAILY_HOSPITAL FOREIGN KEY (hospital_id) REFERENCES hospital (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE kpi_daily DROP CONSTRAINT FK_KPI_DAILY_HOSPITAL');
        $this->addSql('DROP TABLE kpi_daily');
    }
}
