<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260628120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add user_onboarding_step table for participant onboarding progress.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE user_onboarding_step (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, step_key VARCHAR(50) NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_onboarding_step ON user_onboarding_step (user_id, step_key)');
        $this->addSql('CREATE INDEX IDX_USER_ONBOARDING_STEP_USER ON user_onboarding_step (user_id)');
        $this->addSql('ALTER TABLE user_onboarding_step ADD CONSTRAINT FK_USER_ONBOARDING_STEP_USER FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE user_onboarding_step DROP CONSTRAINT FK_USER_ONBOARDING_STEP_USER');
        $this->addSql('DROP TABLE user_onboarding_step');
    }
}
