<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260605103100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add analysis library tables for saved views, favorites, and usage tracking.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE saved_analysis_view (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, owner_id INT NOT NULL, title VARCHAR(180) NOT NULL, description TEXT DEFAULT NULL, config_json JSON NOT NULL, visibility VARCHAR(20) NOT NULL, source_system_view_key VARCHAR(120) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_SAVED_ANALYSIS_VIEW_OWNER ON saved_analysis_view (owner_id)');
        $this->addSql('ALTER TABLE saved_analysis_view ADD CONSTRAINT FK_SAVED_ANALYSIS_VIEW_OWNER FOREIGN KEY (owner_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE favorite_analysis_view (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, source VARCHAR(20) NOT NULL, system_view_key VARCHAR(120) DEFAULT NULL, saved_view_id INT DEFAULT NULL, sort_order INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FAVORITE_ANALYSIS_VIEW_USER ON favorite_analysis_view (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_favorite_system_view ON favorite_analysis_view (user_id, source, system_view_key)');
        $this->addSql('CREATE UNIQUE INDEX uniq_favorite_saved_view ON favorite_analysis_view (user_id, saved_view_id)');
        $this->addSql('ALTER TABLE favorite_analysis_view ADD CONSTRAINT FK_FAVORITE_ANALYSIS_VIEW_USER FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE favorite_analysis_view ADD CONSTRAINT FK_FAVORITE_ANALYSIS_VIEW_SAVED FOREIGN KEY (saved_view_id) REFERENCES saved_analysis_view (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE analysis_view_usage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, source VARCHAR(20) NOT NULL, system_view_key VARCHAR(120) DEFAULT NULL, saved_view_id INT DEFAULT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, use_count INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_ANALYSIS_VIEW_USAGE_USER ON analysis_view_usage (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_usage_system_view ON analysis_view_usage (user_id, source, system_view_key)');
        $this->addSql('CREATE UNIQUE INDEX uniq_usage_saved_view ON analysis_view_usage (user_id, saved_view_id)');
        $this->addSql('ALTER TABLE analysis_view_usage ADD CONSTRAINT FK_ANALYSIS_VIEW_USAGE_USER FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE analysis_view_usage ADD CONSTRAINT FK_ANALYSIS_VIEW_USAGE_SAVED FOREIGN KEY (saved_view_id) REFERENCES saved_analysis_view (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE analysis_view_usage DROP CONSTRAINT FK_ANALYSIS_VIEW_USAGE_SAVED');
        $this->addSql('ALTER TABLE analysis_view_usage DROP CONSTRAINT FK_ANALYSIS_VIEW_USAGE_USER');
        $this->addSql('DROP TABLE analysis_view_usage');
        $this->addSql('ALTER TABLE favorite_analysis_view DROP CONSTRAINT FK_FAVORITE_ANALYSIS_VIEW_SAVED');
        $this->addSql('ALTER TABLE favorite_analysis_view DROP CONSTRAINT FK_FAVORITE_ANALYSIS_VIEW_USER');
        $this->addSql('DROP TABLE favorite_analysis_view');
        $this->addSql('ALTER TABLE saved_analysis_view DROP CONSTRAINT FK_SAVED_ANALYSIS_VIEW_OWNER');
        $this->addSql('DROP TABLE saved_analysis_view');
    }
}
