# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.imports_max_size: '15M'
    app.imports_base_dir: '%kernel.project_dir%/var/imports'
    app.rejects_base_dir: '%kernel.project_dir%/var/imports/rejects'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\Import\Adapter\SplCsvRowReader: ~
    App\Service\Import\Mapping\AllocationRowMapper: ~
    App\Service\Import\Mapping\AllocationImportFactory: ~
    App\Service\Import\Adapter\DoctrineAllocationPersister:
        arguments:
            $batchSize: 250
    App\Service\Import\AllocationImporter:
        arguments:
            $logger: '@monolog.logger.import'
    # App\Service\Import\Adapter\CsvRejectWriter:
    #    arguments:
    #        $baseDir: '%kernel.project_dir%/var/import/rejects'
