<?php

declare(strict_types=1);

namespace App\Tests\Content\Integration\Blog;

use App\Content\Application\Blog\PostSlugResolver;
use App\Content\Application\Slug\SlugGenerator;
use App\Content\Domain\Entity\Post;
use App\Content\Infrastructure\Factory\PostFactory;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Zenstruck\Foundry\Attribute\ResetDatabase;
use Zenstruck\Foundry\Test\Factories;

#[ResetDatabase]
final class PostSlugResolverIntegrationTest extends KernelTestCase
{
    use Factories;

    private PostSlugResolver $resolver;

    #[\Override]
    protected function setUp(): void
    {
        self::bootKernel();
        $this->resolver = self::getContainer()->get(PostSlugResolver::class);
    }

    public function testAutoGeneratedSlugIsUniqueAgainstDatabase(): void
    {
        PostFactory::createOne([
            'title' => 'Popular Title',
            'slug' => 'popular-title',
        ]);

        $post = new Post()->setTitle('Popular Title');

        $this->resolver->resolve($post);

        self::assertSame('popular-title-2', $post->getSlug());
    }

    public function testManualSlugIsNotCheckedForUniqueness(): void
    {
        PostFactory::createOne([
            'title' => 'Existing',
            'slug' => 'manual-slug',
        ]);

        $post = new Post()
            ->setTitle('Another Title')
            ->setSlug('manual-slug');

        $this->resolver->resolve($post);

        self::assertSame('manual-slug', $post->getSlug());
    }

    public function testAutoGeneratedSlugFromLongTitleIsTruncated(): void
    {
        $longTitle = str_repeat('word-', 50).'end';

        $post = new Post()->setTitle($longTitle);

        $this->resolver->resolve($post);

        self::assertLessThanOrEqual(SlugGenerator::MAX_LENGTH_POST, strlen((string) $post->getSlug()));
        self::assertDoesNotMatchRegularExpression('/-$/', (string) $post->getSlug());
    }

    public function testWhitespaceOnlySlugIsTreatedAsEmpty(): void
    {
        $post = new Post()
            ->setTitle('Whitespace Title')
            ->setSlug('   ');

        $this->resolver->resolve($post);

        self::assertSame('whitespace-title', $post->getSlug());
    }
}
